### PR TITLE
Ignore type 'MesRendered' and 'SkinnedMeshRenderer'

### PR DESCRIPTION
**Pull request by Preciel**
When loading CAB/BKL, both 'MesRendered' and 'SkinnedMeshRenderer' type display error in console and consume a lot of RAM from time to time.

If they cannot be read anyway, it would be best to not try to load those types while loading assets.

image

image

image

Bonus: Most users are most likely looking for the sprites, a filter to load only sprites would fasten the process.

### CODE REVIEW

**Comment by khang06** [comment]
did you accidentally pr the wrong repo?

**Comment by Preciel** [comment]
I was redirected and didn't notice @khang06
@Razmoth repo have no issues tab, and when I tried to substitute it with a pull request, I was redirected on your repo...

**Comment by Preciel** [comment]
Btw, if you can delete this pull request @khang06 please.
I will use your issue tab instead, and tag razmoth in it.

**Comment by khang06** [comment]
github doesn't let me delete stuff, only close it

**Pull request closed without merging**
